baseurl = "/"
languageCode = "ja"
title = "美味しい日本酒の研究所 by saketaku"
hasCJKLanguage = true
paginate = 6
enableEmoji = true
[taxonomies]
  tag = "tags"
  category = "categories"


[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "AMP"]